# Generated by Django 5.2.5 on 2025-09-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MfiSsaRmlException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe_date', models.DateField(blank=True, null=True, verbose_name='Universe Date')),
                ('source', models.CharField(blank=True, max_length=6, null=True, verbose_name='Source')),
                ('bond_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bond ID')),
                ('mds_uid', models.CharField(blank=True, max_length=30, null=True, verbose_name='MDS UID')),
                ('error_descr', models.CharField(blank=True, max_length=400, null=True, verbose_name='Error Description')),
                ('tstp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('error_code', models.IntegerField(blank=True, null=True, verbose_name='Error Code')),
            ],
        ),
    ]
